---

- name: POSTGRES | database is created
  become: true
  become_user: postgres
  postgresql_db: 
    name="{{ db_name }}"

- name: POSTGRES | Ensure user has access to the database
  become: true
  become_user: postgres
  postgresql_user: 
    db="{{ db_name }}"
    name="{{ db_user }}"
    password="{{ db_password }}"
    priv=ALL
    

- name: POSTGRES |  Ensure user has access to the database
  become: true
  become_user: postgres
  postgresql_user: 
    db="{{ db_name }}"
    name="{{ db_user }}"
    password="{{ db_password }}"
    priv=ALL
    