---

- name: WORKER | install 
  apt:
    pkg:
      - openjdk-11-jdk


- name: WORKER | Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes
    upgrade: 'yes'

- name: WORKER | Create appWorker directory if it does not exist
  file:
    path: /etc/appWorker
    state: directory
    mode: '0777' 

- name: WORKER | Push worker.zip from master to server
  copy:
    remote_src: no
    src: ../../../worker.zip
    dest: /etc/appWorker/worker.zip
    mode: '0777'
    owner: "{{ user_ansible }}"

- name: WORKER | unarchive worker.zip
  unarchive:
    src: /etc/appWorker/worker.zip
    dest: /etc/appWorker
    remote_src: yes

