---

- name: POLL | install 
  apt:
    pkg:
      - python-pip


- name: POLL | Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes
    upgrade: 'yes'

- name: POLL | Create appPoll directory if it does not exist
  file:
    path: /etc/appPoll
    state: directory
    mode: '0755'

- name: POLL | Push poll.zip from master to server
  copy:
    remote_src: no
    src: ../../../poll.zip
    dest: /etc/appPoll/poll.zip
    mode: preserve
    owner: "{{ user_ansible }}"

- name: POLL | unarchive result.zip
  unarchive:
    src: /etc/appPoll/poll.zip
    dest: /etc/appPoll
    remote_src: yes

- name: POLL | Install requirements
  pip:
    requirements: /etc/appPoll/poll/requirements.txt