---

- name: POLL | save systemd/system into systemd/system-defaut
  copy: 
    src: /etc/systemd/system/
    dest: /etc/systemd/system-default
    directory_mode: 
    owner: "{{ user_ansible }}"
    group: "{{ groupe_ansible }}"
    mode: preserve 
    remote_src: yes

- name: POLL | Copy poll.service in systemd/system
  copy:
    src: ../files/poll.service
    dest: /etc/systemd/system/poll.service
    owner: "{{ user_ansible }}"
    group: "{{ groupe_ansible }}"
    mode: '0644'